language: php

sudo: false

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm

env:
  - test_python=2.6.9 setup=basic
  - test_python=2.6.9 setup=stable
  - test_python=2.6.9 setup=lowest
  - test_python=2.7.13 setup=basic
  - test_python=2.7.13 setup=stable
  - test_python=2.7.13 setup=lowest
  - test_python=3.2.6 setup=basic
  - test_python=3.2.6 setup=stable
  - test_python=3.2.6 setup=lowest
  - test_python=3.3.6 setup=basic
  - test_python=3.3.6 setup=stable
  - test_python=3.3.6 setup=lowest
  - test_python=3.4.5 setup=basic
  - test_python=3.4.5 setup=stable
  - test_python=3.4.5 setup=lowest
  - test_python=3.5.2 setup=basic
  - test_python=3.5.2 setup=stable
  - test_python=3.5.2 setup=lowest
  - test_python=pypy2-5.6.0 setup=basic
  - test_python=pypy2-5.6.0 setup=stable
  - test_python=pypy2-5.6.0 setup=lowest
  - test_python=pypy3-2.4.0 setup=basic
  - test_python=pypy3-2.4.0 setup=stable
  - test_python=pypy3-2.4.0 setup=lowest

before_install:
  - curl -L https://raw.githubusercontent.com/yyuu/pyenv-installer/master/bin/pyenv-installer | bash
  - export PATH="/home/travis/.pyenv/bin:$PATH"
  - eval "$(pyenv init -)"
  - eval "$(pyenv virtualenv-init -)"
  - pyenv install --list
  - pyenv install $test_python
  - python --version

install:
  - if [[ $setup = 'basic' ]]; then travis_retry composer install --no-interaction; fi
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --no-interaction --prefer-stable; fi
  - if [[ $setup = 'lowest' ]]; then travis_retry composer update --no-interaction --prefer-stable --prefer-lowest; fi

script: ./vendor/bin/phpunit

after_success: ./vendor/bin/coveralls
