language: php

sudo: false

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm

env:
  - test_python=2.6 setup=basic
  - test_python=2.6 setup=stable
  - test_python=2.6 setup=lowest
  - test_python=2.7 setup=basic
  - test_python=2.7 setup=stable
  - test_python=2.7 setup=lowest
  - test_python=3.2 setup=basic
  - test_python=3.2 setup=stable
  - test_python=3.2 setup=lowest
  - test_python=3.3 setup=basic
  - test_python=3.3 setup=stable
  - test_python=3.3 setup=lowest
  - test_python=3.4 setup=basic
  - test_python=3.4 setup=stable
  - test_python=3.4 setup=lowest
  - test_python=3.5 setup=basic
  - test_python=3.5 setup=stable
  - test_python=3.5 setup=lowest
  - test_python=pypy setup=basic
  - test_python=pypy setup=stable
  - test_python=pypy setup=lowest

before_install:
  - curl -L https://raw.githubusercontent.com/yyuu/pyenv-installer/master/bin/pyenv-installer | bash
  - export PATH="/home/travis/.pyenv/bin:$PATH"
  - eval "$(pyenv init -)"
  - eval "$(pyenv virtualenv-init -)"
  - pyenv install $test_python

install:
  - if [[ $setup = 'basic' ]]; then travis_retry composer install --no-interaction; fi
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --no-interaction --prefer-stable; fi
  - if [[ $setup = 'lowest' ]]; then travis_retry composer update --no-interaction --prefer-stable --prefer-lowest; fi

script: ./vendor/bin/phpunit

after_success: ./vendor/bin/coveralls
