language: php

sudo: false

os:
  - linux
  - osx

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm

python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - 3.5

env:
  - setup=basic
  - setup=stable
  - setup=lowest

matrix:
  include:
    - os: linux
      dist: trusty

install:
  - if [[ $setup = 'basic' ]]; then travis_retry composer install --no-interaction; fi
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --no-interaction --prefer-stable; fi
  - if [[ $setup = 'lowest' ]]; then travis_retry composer update --no-interaction --prefer-stable --prefer-lowest; fi

script: ./vendor/bin/phpunit

after_success: ./vendor/bin/coveralls
